name: Build Binaries for All Platforms

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: talc-linux
            file_name: talc
          - os: windows-latest
            artifact_name: talc-windows.exe
            file_name: talc.exe
          - os: macos-latest
            artifact_name: talc-macos
            file_name: talc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Build binary with PyInstaller
        run: |
          poetry run pyinstaller --onefile --name ${{ matrix.file_name }} src/talculate/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.file_name }}

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.file_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }}
